const ANDCtree = {
c4: [ 'AND',
  [ 'NOT',
    [ 'AND',
      [ 'NOT',
        [ 'OR',
          [ 'OR',
            [ 'OR',
              [ 'AND',
                [ 'AND', 'a3', [ 'NOT', [ 'AND', [ 'NOT', 'b3' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b3' ] ] ],
              [ 'AND',
                [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ],
            [ 'AND',
              [ 'AND', 'a1', [ 'NOT', [ 'AND', [ 'NOT', 'b1' ], [ 'NOT', 's0' ] ] ] ],
              [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b1' ] ] ] ],
          [ 'AND',
            [ 'NOT', [ 'OR', [ 'NOT', 'a0' ], [ 'AND', [ 'NOT', 'b0' ], [ 'NOT', 's0' ] ] ] ],
            [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b0' ] ] ] ] ],
      [ 'NOT', 'c0' ] ] ],
  [ 'NOT',
    [ 'OR',
      [ 'AND',
        [ 'NOT',
          [ 'OR',
            [ 'OR',
              [ 'NOT',
                [ 'AND',
                  [ 'AND', 'a3', [ 'NOT', [ 'AND', [ 'NOT', 'b3' ], [ 'NOT', 's0' ] ] ] ],
                  [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b3' ] ] ] ],
              [ 'NOT',
                [ 'AND',
                  [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
                  [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ] ],
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a1', [ 'NOT', [ 'AND', [ 'NOT', 'b1' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b1' ] ] ] ] ] ],
        [ 'NOT',
          [ 'AND',
            [ 'NOT', [ 'AND', [ 'NOT', [ 'OR', [ 'NOT', 'b0' ], 'a0' ] ], [ 'NOT', 's2' ] ] ],
            [ 'NOT', [ 'AND', [ 'NOT', [ 'OR', 'a0', 'b0' ] ], [ 'NOT', 's3' ] ] ] ] ] ],
      [ 'AND',
        [ 'NOT',
          [ 'OR',
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a3', [ 'NOT', [ 'AND', [ 'NOT', 'b3' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b3' ] ] ] ],
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ] ] ],
        [ 'NOT',
          [ 'AND',
            [ 'NOT', [ 'AND', [ 'NOT', [ 'OR', [ 'NOT', 'b1' ], 'a1' ] ], [ 'NOT', 's2' ] ] ],
            [ 'NOT', [ 'AND', [ 'NOT', [ 'OR', 'a1', 'b1' ] ], [ 'NOT', 's3' ] ] ] ] ] ],
      [ 'AND',
        [ 'AND',
          [ 'AND', 'a3', [ 'NOT', [ 'AND', [ 'NOT', 'b3' ], [ 'NOT', 's0' ] ] ] ],
          [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b3' ] ] ],
        [ 'NOT',
          [ 'AND',
            [ 'NOT', [ 'AND', [ 'NOT', [ 'OR', [ 'NOT', 'b2' ], 'a2' ] ], [ 'NOT', 's2' ] ] ],
            [ 'NOT', [ 'AND', [ 'NOT', [ 'OR', 'a2', 'b2' ] ], [ 'NOT', 's3' ] ] ] ] ] ],
      [ 'OR',
        [ 'AND', [ 'NOT', [ 'OR', [ 'NOT', 'b3' ], 'a3' ] ], [ 'NOT', 's2' ] ],
        [ 'AND', [ 'NOT', [ 'OR', 'a3', 'b3' ] ], [ 'NOT', 's3' ] ] ] ] ] ],
g: [ 'AND',
  [ 'NOT',
    [ 'AND',
      [ 'AND',
        [ 'NOT',
          [ 'OR',
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a3', [ 'NOT', [ 'AND', [ 'NOT', 'b3' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b3' ] ] ] ],
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ] ] ],
        [ 'AND',
          [ 'AND', 'a1', [ 'NOT', [ 'AND', [ 'NOT', 'b1' ], [ 'NOT', 's0' ] ] ] ],
          [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b1' ] ] ] ],
      [ 'NOT',
        [ 'AND',
          [ 'NOT', [ 'AND', [ 'AND', 'b0', [ 'NOT', 'a0' ] ], [ 'NOT', 's2' ] ] ],
          [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a0' ], [ 'NOT', 'b0' ] ], [ 'NOT', 's3' ] ] ] ] ] ] ],
  [ 'NOT',
    [ 'AND',
      [ 'AND',
        [ 'AND',
          [ 'AND', 'a3', [ 'NOT', [ 'AND', [ 'NOT', 'b3' ], [ 'NOT', 's0' ] ] ] ],
          [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b3' ] ] ],
        [ 'AND',
          [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
          [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ],
      [ 'NOT',
        [ 'AND',
          [ 'NOT', [ 'AND', [ 'AND', 'b1', [ 'NOT', 'a1' ] ], [ 'NOT', 's2' ] ] ],
          [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a1' ], [ 'NOT', 'b1' ] ], [ 'NOT', 's3' ] ] ] ] ] ] ],
  [ 'NOT',
    [ 'AND',
      [ 'AND',
        [ 'AND', 'a3', [ 'NOT', [ 'AND', [ 'NOT', 'b3' ], [ 'NOT', 's0' ] ] ] ],
        [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b3' ] ] ],
      [ 'NOT',
        [ 'AND',
          [ 'NOT', [ 'AND', [ 'AND', 'b2', [ 'NOT', 'a2' ] ], [ 'NOT', 's2' ] ] ],
          [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a2' ], [ 'NOT', 'b2' ] ], [ 'NOT', 's3' ] ] ] ] ] ] ],
  [ 'NOT',
    [ 'OR',
      [ 'AND', [ 'AND', 'b3', [ 'NOT', 'a3' ] ], [ 'NOT', 's2' ] ],
      [ 'AND', [ 'AND', [ 'NOT', 'a3' ], [ 'NOT', 'b3' ] ], [ 'NOT', 's3' ] ] ] ] ],
p: [ 'AND',
  [ 'NOT',
    [ 'OR',
      [ 'OR',
        [ 'NOT',
          [ 'AND',
            [ 'AND', 'a3', [ 'NOT', [ 'AND', [ 'NOT', 'b3' ], [ 'NOT', 's0' ] ] ] ],
            [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b3' ] ] ] ],
        [ 'NOT',
          [ 'AND',
            [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
            [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ] ],
      [ 'NOT',
        [ 'AND',
          [ 'AND', 'a1', [ 'NOT', [ 'AND', [ 'NOT', 'b1' ], [ 'NOT', 's0' ] ] ] ],
          [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b1' ] ] ] ] ] ],
  [ 'AND',
    [ 'AND', 'a0', [ 'NOT', [ 'AND', [ 'NOT', 'b0' ], [ 'NOT', 's0' ] ] ] ],
    [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b0' ] ] ] ],
f3: [ 'NOT',
  [ 'XOR',
    [ 'XOR',
      [ 'NOT',
        [ 'AND',
          [ 'AND', 'a0', [ 'NOT', [ 'AND', [ 'NOT', 'b0' ], [ 'NOT', 's0' ] ] ] ],
          [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b0' ] ] ] ],
      [ 'NOT',
        [ 'AND',
          [ 'NOT', [ 'AND', [ 'AND', 'b0', [ 'NOT', 'a0' ] ], [ 'NOT', 's2' ] ] ],
          [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a0' ], [ 'NOT', 'b0' ] ], [ 'NOT', 's3' ] ] ] ] ] ],
    [ 'AND', [ 'NOT', 'c0' ], [ 'NOT', 'm' ] ] ] ],
f2: [ 'NOT',
  [ 'XOR',
    [ 'XOR',
      [ 'NOT',
        [ 'AND',
          [ 'AND', 'a1', [ 'NOT', [ 'AND', [ 'NOT', 'b1' ], [ 'NOT', 's0' ] ] ] ],
          [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b1' ] ] ] ],
      [ 'NOT',
        [ 'AND',
          [ 'NOT', [ 'AND', [ 'AND', 'b1', [ 'NOT', 'a1' ] ], [ 'NOT', 's2' ] ] ],
          [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a1' ], [ 'NOT', 'b1' ] ], [ 'NOT', 's3' ] ] ] ] ] ],
    [ 'OR',
      [ 'AND',
        [ 'NOT',
          [ 'OR',
            'c0',
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a0', [ 'NOT', [ 'AND', [ 'NOT', 'b0' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b0' ] ] ] ] ] ],
        [ 'NOT', 'm' ] ],
      [ 'AND',
        [ 'AND',
          [ 'NOT', [ 'AND', [ 'AND', 'b0', [ 'NOT', 'a0' ] ], [ 'NOT', 's2' ] ] ],
          [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a0' ], [ 'NOT', 'b0' ] ], [ 'NOT', 's3' ] ] ] ],
        [ 'NOT', 'm' ] ] ] ] ],
f1: [ 'NOT',
  [ 'XOR',
    [ 'XOR',
      [ 'NOT',
        [ 'AND',
          [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
          [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ],
      [ 'NOT',
        [ 'AND',
          [ 'NOT', [ 'AND', [ 'AND', 'b2', [ 'NOT', 'a2' ] ], [ 'NOT', 's2' ] ] ],
          [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a2' ], [ 'NOT', 'b2' ] ], [ 'NOT', 's3' ] ] ] ] ] ],
    [ 'OR',
      [ 'AND',
        [ 'NOT',
          [ 'OR',
            [ 'OR',
              'c0',
              [ 'NOT',
                [ 'AND',
                  [ 'AND', 'a1', [ 'NOT', [ 'AND', [ 'NOT', 'b1' ], [ 'NOT', 's0' ] ] ] ],
                  [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b1' ] ] ] ] ],
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a0', [ 'NOT', [ 'AND', [ 'NOT', 'b0' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b0' ] ] ] ] ] ],
        [ 'NOT', 'm' ] ],
      [ 'AND',
        [ 'NOT',
          [ 'OR',
            [ 'NOT',
              [ 'AND',
                [ 'NOT', [ 'AND', [ 'AND', 'b0', [ 'NOT', 'a0' ] ], [ 'NOT', 's2' ] ] ],
                [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a0' ], [ 'NOT', 'b0' ] ], [ 'NOT', 's3' ] ] ] ] ],
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a1', [ 'NOT', [ 'AND', [ 'NOT', 'b1' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b1' ] ] ] ] ] ],
        [ 'NOT', 'm' ] ],
      [ 'AND',
        [ 'AND',
          [ 'NOT', [ 'AND', [ 'AND', 'b1', [ 'NOT', 'a1' ] ], [ 'NOT', 's2' ] ] ],
          [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a1' ], [ 'NOT', 'b1' ] ], [ 'NOT', 's3' ] ] ] ],
        [ 'NOT', 'm' ] ] ] ] ],
f0: [ 'NOT',
  [ 'XOR',
    [ 'XOR',
      [ 'NOT',
        [ 'AND',
          [ 'AND', 'a3', [ 'NOT', [ 'AND', [ 'NOT', 'b3' ], [ 'NOT', 's0' ] ] ] ],
          [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b3' ] ] ] ],
      [ 'AND',
        [ 'NOT', [ 'AND', [ 'AND', 'b3', [ 'NOT', 'a3' ] ], [ 'NOT', 's2' ] ] ],
        [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a3' ], [ 'NOT', 'b3' ] ], [ 'NOT', 's3' ] ] ] ] ],
    [ 'OR',
      [ 'AND',
        [ 'NOT',
          [ 'OR',
            [ 'OR',
              [ 'OR',
                'c0',
                [ 'NOT',
                  [ 'AND',
                    [ 'AND', 'a0', [ 'NOT', [ 'AND', [ 'NOT', 'b0' ], [ 'NOT', 's0' ] ] ] ],
                    [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b0' ] ] ] ] ],
              [ 'NOT',
                [ 'AND',
                  [ 'AND', 'a1', [ 'NOT', [ 'AND', [ 'NOT', 'b1' ], [ 'NOT', 's0' ] ] ] ],
                  [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b1' ] ] ] ] ],
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ] ] ],
        [ 'NOT', 'm' ] ],
      [ 'AND',
        [ 'NOT',
          [ 'OR',
            [ 'OR',
              [ 'NOT',
                [ 'AND',
                  [ 'NOT', [ 'AND', [ 'AND', 'b0', [ 'NOT', 'a0' ] ], [ 'NOT', 's2' ] ] ],
                  [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a0' ], [ 'NOT', 'b0' ] ], [ 'NOT', 's3' ] ] ] ] ],
              [ 'NOT',
                [ 'AND',
                  [ 'AND', 'a1', [ 'NOT', [ 'AND', [ 'NOT', 'b1' ], [ 'NOT', 's0' ] ] ] ],
                  [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b1' ] ] ] ] ],
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ] ] ],
        [ 'NOT', 'm' ] ],
      [ 'AND',
        [ 'NOT',
          [ 'OR',
            [ 'NOT',
              [ 'AND',
                [ 'NOT', [ 'AND', [ 'AND', 'b1', [ 'NOT', 'a1' ] ], [ 'NOT', 's2' ] ] ],
                [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a1' ], [ 'NOT', 'b1' ] ], [ 'NOT', 's3' ] ] ] ] ],
            [ 'NOT',
              [ 'AND',
                [ 'AND', 'a2', [ 'NOT', [ 'AND', [ 'NOT', 'b2' ], [ 'NOT', 's0' ] ] ] ],
                [ 'NOT', [ 'AND', [ 'NOT', 's1' ], 'b2' ] ] ] ] ] ],
        [ 'NOT', 'm' ] ],
      [ 'AND',
        [ 'AND',
          [ 'NOT', [ 'AND', [ 'AND', 'b2', [ 'NOT', 'a2' ] ], [ 'NOT', 's2' ] ] ],
          [ 'NOT', [ 'AND', [ 'AND', [ 'NOT', 'a2' ], [ 'NOT', 'b2' ] ], [ 'NOT', 's3' ] ] ] ],
        [ 'NOT', 'm' ] ] ] ] ],
};
module.exports = {ANDCtree};
